### ISSUE TITLE
[Enhancement] Allow config of the log rounds via the gen salt method like jBCrypt

### ISSUE THREAD

**Issue by AMcBain** [Yun56/node-bcrypt#1]
Would be nice if like JBCrypt ( http://www.mindrot.org/files/jBCrypt/jBCrypt-0.2-doc/ ) the gensalt function could take a parameter indicating the value of GENSALT_DEFAULT_LOG2_ROUNDS the caller wishes to use for just that salt.

It seems from the source all jBCrypt does there is prepend a zero if the value is < 10. The actual range checking of the number is left up, like node-bcrypt, to the hashpw function.

**Comment by kurten** [comment]
Because of the performance. I am not going to work on this. We use this now https://github.com/ncb000gt/node.bcrypt.js.
